[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "target-feature=+sse4.1"]

[target.x86_64-pc-windows-gnu]
rustflags = ["-C", "target-feature=+sse4.1"]

[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+sse4.1"]

[target.aarch64-unknown-linux-gnu]
rustflags = ["-C", "target-feature=+neon"]

[target.aarch64-apple-darwin]
rustflags = ["-C", "target-feature=+neon"]
